#此工作流程将使用Maven构建一个包，然后在创建发行版时将其发布到GitHub包
#有关更多信息，请参见:https://github . com/actions/setup-Java/blob/main/docs/advanced-usage . MD # Apache-maven-with-a-settings-path

名字: Maven包

在:
释放；排放；发布:
类型: [创造]

工作:
建设:

连续运行: Ubuntu-最新版
许可:
内容: 阅读
包装: 写

步伐:
    - 使用: 动作/签出@v3
    - 名字: 建立JDK 11号
使用: 操作/设置-java@v3
随着:
java版本: '11'
分布: 特穆林
服务器id: 开源代码库pom.xml的distribution management/repository/id字段的值
设置-路径: ${{github.workspace}} #设置。xml文件的位置

    - 名字: 用Maven构建
奔跑: mvn -B包文件pom.xml

    - 名字: 发布到GitHub包Apache Maven
奔跑: mvn deploy-s $ GITHUB _ WORKSPACE/settings . XML
包封/包围（动词envelop的简写）:
GITHUB_TOKEN: ${{github.token}}
